export const featureStories = [
  {
    id: "GEN-001",
    area: "generic",
    feature: "Generate Nostr key material",
    commands: "keygen",
    story: "As a CLI user, I want to generate a fresh Nostr secret and all public-key formats needed by Nowhere.",
    expectedBehavior: "The command emits a new secret in hex and nsec form plus pubkeyHex, npub, and nowherePubkey, with optional JSON formatting.",
    keyFlags: "--json",
    codeRef: "src/cli.ts:626-642",
    tests: "tests/e2e/generic.test.ts:keygen emits the expected Nostr and Nowhere formats",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-002",
    area: "generic",
    feature: "Derive pubkey formats from a secret",
    commands: "pubkey",
    story: "As a CLI user, I want to derive the public-key forms for an existing Nostr secret without recreating the keypair.",
    expectedBehavior: "The command requires --secret and emits pubkeyHex, npub, and nowherePubkey for the provided nsec or hex secret.",
    keyFlags: "--secret, --json",
    codeRef: "src/cli.ts:644-659",
    tests: "tests/e2e/generic.test.ts:pubkey derives the expected public-key formats from an existing secret",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-003",
    area: "generic",
    feature: "Inspect fragments and URLs",
    commands: "inspect",
    story: "As a CLI user, I want to inspect a Nowhere fragment or URL and see its decoded site metadata and verification state.",
    expectedBehavior: "The command normalizes the input, optionally decrypts it, fails on decode errors, and prints fragment, URL, site metadata, signature info, and verification summary.",
    keyFlags: "--password, --json",
    codeRef: "src/cli.ts:661-697",
    tests: "tests/e2e/generic.test.ts:inspect exposes decoded site data and verification phrases",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-004",
    area: "signer",
    feature: "Connect a persisted remote signer",
    commands: "signer connect",
    story: "As a CLI user, I want to connect a NIP-46 signer by bunker URI or name@domain and persist it for later commands.",
    expectedBehavior: "The command requires --bunker, persists the signer session, prints connected status with type and public keys, and cleans up the live connection afterward.",
    keyFlags: "--bunker, --json",
    codeRef: "src/cli.ts:699-723; src/lib/active-signer.ts",
    tests: "tests/e2e/builders.test.ts:sign create and update can use a persisted remote signer session",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct connect output and persisted session lifecycle are asserted in builders coverage."
  },
  {
    id: "GEN-005",
    area: "signer",
    feature: "Inspect persisted signer status",
    commands: "signer status",
    story: "As a CLI user, I want to inspect whether a remote signer session is currently persisted and reusable.",
    expectedBehavior: "The command prints the persisted signer status and tears down shared relay state on exit.",
    keyFlags: "--json",
    codeRef: "src/cli.ts:725-735; src/lib/active-signer.ts",
    tests: "tests/e2e/builders.test.ts:sign create and update can use a persisted remote signer session",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct status output is asserted in builders coverage."
  },
  {
    id: "GEN-006",
    area: "signer",
    feature: "Disconnect the persisted signer",
    commands: "signer disconnect",
    story: "As a CLI user, I want to forget a persisted remote signer session so later commands stop reusing it.",
    expectedBehavior: "The command clears the persisted signer file and returns the disconnect status.",
    keyFlags: "--json",
    codeRef: "src/cli.ts:737-747; src/lib/active-signer.ts",
    tests: "tests/e2e/builders.test.ts:sign create and update can use a persisted remote signer session",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct disconnect behavior is asserted in builders coverage."
  },
  {
    id: "GEN-007",
    area: "generic",
    feature: "Sign an existing fragment",
    commands: "sign",
    story: "As a CLI user, I want to sign an unsigned Nowhere fragment with either a local secret or the active remote signer.",
    expectedBehavior: "The command requires either --secret or --use-signer, rejects conflicting signer inputs, verifies the embedded site pubkey if present, and returns signed and unsigned URLs plus signer identities.",
    keyFlags: "--secret, --use-signer, --json",
    codeRef: "src/cli.ts:482-535, 749-763",
    tests: "tests/e2e/generic.test.ts:sign and verify round-trip a Nowhere fragment; tests/e2e/builders.test.ts:sign create and update can use a persisted remote signer session",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Wrong-key failure path is not directly covered."
  },
  {
    id: "GEN-008",
    area: "generic",
    feature: "Verify a signed fragment",
    commands: "verify",
    story: "As a CLI user, I want to verify the signature state of a signed Nowhere fragment or URL.",
    expectedBehavior: "The command optionally decrypts the input, fails on decode errors, and returns whether the fragment is signed, the signer pubkey, the unsigned fragment, and a verification summary.",
    keyFlags: "--password, --json",
    codeRef: "src/cli.ts:765-788",
    tests: "tests/e2e/generic.test.ts:sign and verify round-trip a Nowhere fragment",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Invalid-signature and malformed-input paths are not directly covered."
  },
  {
    id: "GEN-009",
    area: "create",
    feature: "Create any supported site type from structured JSON",
    commands: "create",
    story: "As a CLI user, I want to create any of the eight Nowhere site types from structured JSON and optionally sign or encrypt the result.",
    expectedBehavior: "The command accepts only the supported tool slugs, reads JSON from a file or stdin, builds the site through the upstream codec, optionally signs or encrypts it, and returns the resulting fragment, URLs, siteData, and verification details.",
    keyFlags: "--input, --sign-secret, --use-signer, --encrypt-password, --json",
    codeRef: "src/cli.ts:790-843",
    tests: "tests/e2e/builders.test.ts:create store preserves items and supports signing; create petition accepts a real key and can encrypt after signing; create forum preserves boolean tags encoded through null values",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Builder coverage on main exercises event, fundraiser, message, drop, art, store, petition, and forum create flows."
  },
  {
    id: "GEN-010",
    area: "create",
    feature: "Create a drop from long-form flags",
    commands: "create drop",
    story: "As a CLI user, I want to build a drop without a JSON file by passing long-form flags on the command line.",
    expectedBehavior: "The command resolves long-form create options into raw site input, builds the drop, and rejects unsupported flag combinations.",
    keyFlags: "--name, --description, --image, --pubkey, --tag, --json",
    codeRef: "src/cli.ts:790-843; src/lib/create-long-form.ts",
    tests: "tests/e2e/create-long-form.test.ts:builds a drop from explicit flags without a JSON file",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-011",
    area: "create",
    feature: "Create art from inline or file-backed SVG",
    commands: "create art",
    story: "As a CLI user, I want to build an art site using inline SVG or an SVG file instead of hand-authoring raw JSON.",
    expectedBehavior: "The command accepts --svg or --svg-file in long-form mode and includes the SVG in the built art site.",
    keyFlags: "--svg, --svg-file, --json",
    codeRef: "src/cli.ts:806-811; src/lib/create-long-form.ts",
    tests: "tests/e2e/create-long-form.test.ts:reads SVG markup for art sites from a file",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Inline SVG path is implied by code but not directly covered."
  },
  {
    id: "GEN-012",
    area: "create",
    feature: "Create store items from long-form flags",
    commands: "create store",
    story: "As a CLI user, I want to define store items and infer ownership from the signing secret while using long-form create flags.",
    expectedBehavior: "The command parses repeated --item specs, preserves store items in the built site, and can infer the owner pubkey from the signing secret when long-form create is used.",
    keyFlags: "--item, --sign-secret, --use-signer, --json",
    codeRef: "src/cli.ts:800-811; src/lib/create-long-form.ts",
    tests: "tests/e2e/create-long-form.test.ts:preserves store items and infers the owner pubkey from the signing secret",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-013",
    area: "create",
    feature: "Reject mixed JSON and long-form create modes",
    commands: "create",
    story: "As a CLI user, I want the CLI to reject ambiguous create input when I mix JSON mode with long-form flags.",
    expectedBehavior: "The command fails when --input is combined with long-form builder flags that should be mutually exclusive.",
    keyFlags: "--input plus long-form flags",
    codeRef: "src/lib/create-long-form.ts",
    tests: "tests/e2e/create-long-form.test.ts:rejects mixing JSON input with long-form builder flags",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-014",
    area: "generic",
    feature: "Update an existing site by patching decoded data",
    commands: "update",
    story: "As a CLI user, I want to import an existing site, merge a JSON patch into the decoded site data, and republish it.",
    expectedBehavior: "The command resolves and optionally decrypts the input site, reads a JSON patch, deep-merges it into siteData, rebuilds the site with the matching tool slug, and optionally signs or encrypts the result.",
    keyFlags: "--patch, --password, --sign-secret, --use-signer, --encrypt-password, --json",
    codeRef: "src/cli.ts:845-890",
    tests: "tests/e2e/builders.test.ts:update imports an existing site merges a patch and republishes it",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-015",
    area: "generic",
    feature: "Encrypt a fragment",
    commands: "encrypt",
    story: "As a CLI user, I want to password-encrypt a Nowhere fragment or URL for transport or sharing.",
    expectedBehavior: "The command normalizes the fragment, encrypts it with the provided password, and returns both the encrypted fragment and URL.",
    keyFlags: "--password, --json",
    codeRef: "src/cli.ts:892-908",
    tests: "tests/e2e/generic.test.ts:encrypt and decrypt round-trip a fragment losslessly",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "GEN-016",
    area: "generic",
    feature: "Decrypt a fragment",
    commands: "decrypt",
    story: "As a CLI user, I want to decrypt an encrypted Nowhere fragment or URL back to its usable form.",
    expectedBehavior: "The command normalizes the input, decrypts it with the provided password, and returns the plaintext fragment and URL.",
    keyFlags: "--password, --json",
    codeRef: "src/cli.ts:910-925",
    tests: "tests/e2e/generic.test.ts:encrypt and decrypt round-trip a fragment losslessly",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Wrong-password behavior is not directly covered."
  },
  {
    id: "STR-001",
    area: "store",
    feature: "Publish a store order and return the seller receipt",
    commands: "store order",
    story: "As a buyer-side automation user, I want to publish an encrypted store order and receive the seller receipt payload.",
    expectedBehavior: "The command resolves the store, reads an order payload from JSON or stdin, converts major-unit totals into cents where required, publishes the order through relays, and returns the receipt payload.",
    keyFlags: "--input, --password, --relay, --json",
    codeRef: "src/cli.ts:930-968",
    tests: "tests/e2e/live-commands.test.ts:store commands publish orders decrypt receipts and manage status",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "STR-002",
    area: "store",
    feature: "Decrypt a store receipt",
    commands: "store receipt decrypt",
    story: "As a seller-side user, I want to decrypt a receipt payload with my local secret or active signer access.",
    expectedBehavior: "The command accepts either a raw receipt string or a receipt object with v, p, and c fields, then decrypts it with the seller secret or signer access.",
    keyFlags: "--input, --secret, --use-signer, --json",
    codeRef: "src/cli.ts:970-1006",
    tests: "tests/e2e/live-commands.test.ts:store commands publish orders decrypt receipts and manage status",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "STR-003",
    area: "store",
    feature: "Fetch seller-visible store orders",
    commands: "store orders",
    story: "As a seller-side user, I want to fetch decrypted orders for a store and optionally target specific order ids or export CSV.",
    expectedBehavior: "The command resolves the store, uses a seller secret or signer when provided, fetches either targeted order ids or the seller feed, supports relay and time filtering, and can print JSON or CSV.",
    keyFlags: "--secret, --use-signer, --order-id, --since, --until, --limit, --csv, --json",
    codeRef: "src/cli.ts:1008-1055",
    tests: "tests/e2e/live-commands.test.ts:store commands publish orders decrypt receipts and manage status; tests/e2e/store-live.test.ts:fetches specific seller orders by their order ids",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "STR-004",
    area: "store",
    feature: "Verify store receipts events or raw orders",
    commands: "store verify",
    story: "As a seller-side user, I want to verify a receipt, encrypted order event, or raw order JSON against the store rules.",
    expectedBehavior: "The command resolves the store, reads the payload, decrypts when signer access is needed, and evaluates the order against store totals and optional historical rate overrides.",
    keyFlags: "--input, --secret, --use-signer, --received-sats, --store-sats-per-unit, --payment-sats-per-unit, --json",
    codeRef: "src/cli.ts:1057-1092",
    tests: "tests/e2e/live-commands.test.ts:store commands publish orders decrypt receipts and manage status; tests/e2e/store-live.test.ts:verifies receipt payloads against the store with historical rate overrides",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Negative mismatch cases are thin."
  },
  {
    id: "STR-005",
    area: "store",
    feature: "Quote checkout requirements and totals",
    commands: "store checkout quote",
    story: "As a buyer-side user, I want to quote checkout totals, buyer-field requirements, and payment-method availability before creating an order.",
    expectedBehavior: "The command resolves the store, reads a cart payload, queries relay-backed status when needed, and returns subtotal, shipping, discount, total, inventory gating, and buyer-country effects.",
    keyFlags: "--cart, --buyer-country, --password, --relay, --json",
    codeRef: "src/cli.ts:1094-1118",
    tests: "tests/e2e/store-live.test.ts:quotes checkout requirements and begins lightning manual checkout flows",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "STR-006",
    area: "store",
    feature: "Begin a checkout flow",
    commands: "store checkout begin",
    story: "As a buyer-side user, I want to start checkout, publish the order, and get back either a Lightning invoice or manual payment instructions.",
    expectedBehavior: "The command resolves the store, reads cart and buyer payloads, starts checkout through the configured payment method, and returns the next-step payment artifact.",
    keyFlags: "--cart, --buyer, --method, --password, --relay, --json",
    codeRef: "src/cli.ts:1120-1143",
    tests: "tests/e2e/store-live.test.ts:quotes checkout requirements and begins lightning manual checkout flows",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Unavailable-method and invalid-cart failures are not directly covered."
  },
  {
    id: "STR-007",
    area: "store",
    feature: "Publish store status",
    commands: "store status publish",
    story: "As a seller-side user, I want to publish encrypted inventory-aware store status updates.",
    expectedBehavior: "The command resolves the store, reads status JSON, preserves the expected v=1 payload shape, and publishes it with seller credentials or the active signer.",
    keyFlags: "--input, --secret, --use-signer, --password, --relay, --json",
    codeRef: "src/cli.ts:1145-1189",
    tests: "tests/e2e/live-commands.test.ts:store commands publish orders decrypt receipts and manage status; tests/e2e/store-live.test.ts:publishes store status payloads and fetches the current decrypted status",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "STR-008",
    area: "store",
    feature: "Fetch current store status",
    commands: "store status fetch",
    story: "As a store operator, I want to fetch the latest encrypted store status so automation can inspect closure, notices, and inventory gates.",
    expectedBehavior: "The command resolves the store and fetches the current relay-backed status payload for the store.",
    keyFlags: "--password, --relay, --json",
    codeRef: "src/cli.ts:1191-1206",
    tests: "tests/e2e/live-commands.test.ts:store commands publish orders decrypt receipts and manage status; tests/e2e/store-live.test.ts:publishes store status payloads and fetches the current decrypted status",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "PET-001",
    area: "petition",
    feature: "Publish a petition signature",
    commands: "petition sign",
    story: "As a signer, I want to submit a petition signature anonymously or with a Nostr key while respecting petition-side validation rules.",
    expectedBehavior: "The command resolves the petition, requires an owner pubkey on the site, reads the signature payload, derives relay defaults from petition tags, enforces PoW difficulty, and publishes via secret or signer when provided.",
    keyFlags: "--input, --secret, --use-signer, --password, --relay, --pow-difficulty, --json",
    codeRef: "src/cli.ts:1208-1252",
    tests: "tests/e2e/live-commands.test.ts:petition commands sign count and decrypt signatures; tests/e2e/petition-live.test.ts:validates petition-required fields and country restrictions from petition tags",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "PET-002",
    area: "petition",
    feature: "Count petition signatures",
    commands: "petition count",
    story: "As a petition owner or observer, I want to count signatures by the petition's derived d-tag.",
    expectedBehavior: "The command resolves the petition, derives relay defaults from petition tags when none are passed, and counts signatures for the petition fragment.",
    keyFlags: "--password, --relay, --json",
    codeRef: "src/cli.ts:1254-1274",
    tests: "tests/e2e/live-commands.test.ts:petition commands sign count and decrypt signatures",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "PET-003",
    area: "petition",
    feature: "Fetch and decrypt petition signatures",
    commands: "petition signatures",
    story: "As a petition owner, I want to fetch owner-visible petition signatures and optionally export them as CSV.",
    expectedBehavior: "The command resolves the petition, uses owner secret or signer access, fetches signatures with PoW filtering, and prints JSON or CSV export output.",
    keyFlags: "--secret, --use-signer, --password, --relay, --pow-difficulty, --csv, --json",
    codeRef: "src/cli.ts:1276-1310",
    tests: "tests/e2e/live-commands.test.ts:petition commands sign count and decrypt signatures; tests/e2e/petition-live.test.ts:counts by petition d-tag and decrypts owner-visible signatures while rejecting insufficient PoW",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FUN-001",
    area: "fundraiser",
    feature: "List fundraiser donation methods",
    commands: "fundraiser donate methods",
    story: "As a donor-side user, I want to inspect the donation methods encoded on a fundraiser site.",
    expectedBehavior: "The command resolves the fundraiser, optionally decrypts it, and returns parsed donation methods from the fundraiser link tag.",
    keyFlags: "--password, --json",
    codeRef: "src/cli.ts:1312-1332",
    tests: "tests/e2e/live-commands.test.ts:fundraiser commands list donation methods; tests/e2e/fundraiser-donate.test.ts:lists donation methods with stable ids",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FUN-002",
    area: "fundraiser",
    feature: "Create a fundraiser Lightning invoice",
    commands: "fundraiser donate invoice",
    story: "As a donor-side user, I want to turn a fundraiser's Lightning method into a live invoice for a sats amount.",
    expectedBehavior: "The command resolves the fundraiser, defaults the method to lightning, parses sats as an integer, and returns the invoice or fails if the chosen method cannot mint invoices.",
    keyFlags: "--method, --sats, --password, --json",
    codeRef: "src/cli.ts:1334-1352",
    tests: "tests/e2e/fundraiser-donate.test.ts:creates fundraiser lightning invoices and rejects custom methods for invoice generation",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct CLI invoice coverage uses an LNURL fetch shim in live-commands."
  },
  {
    id: "MSG-001",
    area: "message",
    feature: "List message tip methods",
    commands: "message tip methods",
    story: "As a reader-side user, I want to inspect the tip methods encoded on a message site.",
    expectedBehavior: "The command resolves the message, optionally decrypts it, and returns parsed tip methods from the message link tag.",
    keyFlags: "--password, --json",
    codeRef: "src/cli.ts:1354-1368",
    tests: "tests/e2e/live-commands.test.ts:message commands list tip methods; tests/e2e/message-tips.test.ts:lists tip methods with stable ids",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "MSG-002",
    area: "message",
    feature: "Create a message tip invoice",
    commands: "message tip invoice",
    story: "As a reader-side user, I want to create a Lightning tip invoice for a message in sats.",
    expectedBehavior: "The command resolves the message, defaults the method to lightning, parses sats as an integer, and returns the invoice or fails if the chosen method is not invoice-capable.",
    keyFlags: "--method, --sats, --password, --json",
    codeRef: "src/cli.ts:1370-1387",
    tests: "tests/e2e/message-tips.test.ts:creates message lightning invoices and rejects custom methods for invoice generation",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct CLI invoice coverage uses an LNURL fetch shim in live-commands."
  },
  {
    id: "FOR-001",
    area: "forum",
    feature: "Check forum WoT access",
    commands: "forum wot check",
    story: "As a moderator or agent, I want to evaluate whether a given author is allowed for a specific forum moderation scope.",
    expectedBehavior: "The command resolves the forum, optionally decrypts it, checks the author against WoT rules for post, reply, chat, or torrent scope, and returns the decision.",
    keyFlags: "--scope, --author, --password, --profile-relay, --json",
    codeRef: "src/cli.ts:1389-1413",
    tests: "tests/e2e/live-commands.test.ts:forum moderation commands expose WOT access checks and moderated post listings",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-002",
    area: "forum",
    feature: "Publish a forum post",
    commands: "forum post",
    story: "As a forum participant, I want to publish a post with optional topic, body, or link data using a local key or signer.",
    expectedBehavior: "The command resolves the forum, reads post JSON, supports secret or signer auth, supports salted namespaces, and publishes the resulting post through the configured relays.",
    keyFlags: "--input, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1415-1448",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-003",
    area: "forum",
    feature: "List forum posts",
    commands: "forum posts",
    story: "As a forum participant, I want to list posts, optionally by topic and with moderation filtering that mirrors the website.",
    expectedBehavior: "The command resolves the forum, optionally scopes to a topic, lists posts for the salted or unsalted namespace, and when --moderated is set filters them through WoT and banned-word rules using the provided profile relays.",
    keyFlags: "--topic, --moderated, --password, --profile-relay, --salt, --relay, --json",
    codeRef: "src/cli.ts:1450-1484",
    tests: "tests/e2e/live-commands.test.ts:forum moderation commands expose WOT access checks and moderated post listings",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-004",
    area: "forum",
    feature: "Publish a forum reply",
    commands: "forum reply",
    story: "As a forum participant, I want to reply to an existing forum post and optionally quote another reply.",
    expectedBehavior: "The command requires the parent post event id, reads reply JSON, supports secret or signer auth, and publishes the reply in the selected forum namespace.",
    keyFlags: "--post-event, --input, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1486-1519",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-005",
    area: "forum",
    feature: "List forum replies",
    commands: "forum replies",
    story: "As a forum participant, I want to list replies for a specific post and optionally apply moderation filtering.",
    expectedBehavior: "The command requires the parent post event id, lists replies for the selected namespace, and when --moderated is set filters them through WoT and banned-word rules.",
    keyFlags: "--post-event, --moderated, --password, --profile-relay, --salt, --relay, --json",
    codeRef: "src/cli.ts:1521-1554",
    tests: "tests/e2e/forum-live.test.ts:publishes and lists replies via post event lookup",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Moderated CLI filtering is asserted directly in live-commands."
  },
  {
    id: "FOR-006",
    area: "forum",
    feature: "Parse a torrent file",
    commands: "forum torrent parse",
    story: "As a forum operator, I want to parse a real .torrent file into the normalized payload fields that Nowhere stores.",
    expectedBehavior: "The command reads the .torrent file, parses it, and returns infohash, inferred title, files, and deduplicated trackers.",
    keyFlags: "--json",
    codeRef: "src/cli.ts:1556-1566",
    tests: "README examples only",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct CLI coverage parses a synthetic .torrent fixture."
  },
  {
    id: "FOR-007",
    area: "forum",
    feature: "Preflight-check a torrent submission",
    commands: "forum torrent check",
    story: "As a forum operator, I want to validate a torrent submission against forum rules and duplicates before publish.",
    expectedBehavior: "The command resolves the forum, builds the torrent payload from file-based inputs, and checks feature enablement, normalized categories, and duplicate conditions before publish.",
    keyFlags: "--torrent-file, --category, --title, --description, --tracker, --ref, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1568-1601",
    tests: "README examples only",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct CLI coverage asserts category normalization, refs, and forum rules."
  },
  {
    id: "FOR-008",
    area: "forum",
    feature: "Publish a forum torrent entry",
    commands: "forum torrent publish",
    story: "As a forum participant, I want to publish a torrent either from raw JSON or from a .torrent file plus CLI metadata flags.",
    expectedBehavior: "The command resolves the forum, accepts either raw JSON or file-derived torrent input, supports signer auth and salted namespaces, and publishes the torrent entry.",
    keyFlags: "--input, --torrent-file, --category, --title, --description, --tracker, --ref, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1603-1639",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "File-derived publish path is asserted directly in live-commands."
  },
  {
    id: "FOR-009",
    area: "forum",
    feature: "Publish a torrent reply",
    commands: "forum torrent reply",
    story: "As a forum participant, I want to reply to an existing torrent entry and optionally quote another reply.",
    expectedBehavior: "The command requires the torrent event id, reads reply JSON, supports secret or signer auth, and publishes the reply in the selected namespace.",
    keyFlags: "--torrent-event, --input, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1641-1674",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-010",
    area: "forum",
    feature: "List torrent replies",
    commands: "forum torrent replies",
    story: "As a forum participant, I want to list replies for a specific torrent entry.",
    expectedBehavior: "The command requires the torrent event id, resolves the forum, and returns torrent replies for the selected salted or unsalted namespace.",
    keyFlags: "--torrent-event, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1676-1698",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-011",
    area: "forum",
    feature: "List forum torrents",
    commands: "forum torrents",
    story: "As a forum participant, I want to list published torrent entries and optionally filter them through moderation rules.",
    expectedBehavior: "The command resolves the forum, lists torrent entries for the selected namespace, and when --moderated is set filters them through WoT and banned-word rules.",
    keyFlags: "--moderated, --password, --profile-relay, --salt, --relay, --json",
    codeRef: "src/cli.ts:1700-1731",
    tests: "tests/e2e/forum-live.test.ts:publishes and lists torrent posts",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Moderated torrent list behavior is asserted directly in live-commands."
  },
  {
    id: "FOR-012",
    area: "forum",
    feature: "Send a general chat message",
    commands: "forum chat send",
    story: "As a forum participant, I want to publish a general chat message and optionally advertise a stable session identity for private follow-up.",
    expectedBehavior: "The command resolves the forum, reads a chat payload, uses secret or signer auth, supports an override session secret, and publishes the chat message.",
    keyFlags: "--input, --secret, --use-signer, --session-secret, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1733-1767; src/lib/forum-session.ts",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat; forum CLI reuses a persisted anonymous session for posts chat routing and private inbox decryption",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "If no session override is supplied, the CLI persists and reuses a forum session secret."
  },
  {
    id: "FOR-013",
    area: "forum",
    feature: "Send a private chat message",
    commands: "forum private send",
    story: "As a forum participant, I want to send an encrypted private message to a recipient's stable session pubkey.",
    expectedBehavior: "The command requires the recipient session pubkey, reads a private-message payload, supports secret or signer auth, and publishes an encrypted private message.",
    keyFlags: "--recipient-session-pubkey, --input, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1769-1804",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-014",
    area: "forum",
    feature: "List private chat messages",
    commands: "forum private list",
    story: "As a forum participant, I want to decrypt and list private messages for the persisted or overridden forum session.",
    expectedBehavior: "The command resolves the forum, uses the persisted forum session secret unless overridden, optionally filters by peer pubkey, and returns decrypted private messages.",
    keyFlags: "--session-secret, --peer-pubkey, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1806-1830; src/lib/forum-session.ts",
    tests: "tests/e2e/live-commands.test.ts:forum CLI reuses a persisted anonymous session for posts chat routing and private inbox decryption",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Peer filtering is not directly covered."
  },
  {
    id: "FOR-015",
    area: "forum",
    feature: "List general chat messages",
    commands: "forum chat list",
    story: "As a forum participant, I want to list general chat messages and optionally filter them through moderation rules.",
    expectedBehavior: "The command resolves the forum, lists chat messages for the selected namespace, and when --moderated is set filters them through WoT and banned-word rules.",
    keyFlags: "--moderated, --password, --profile-relay, --salt, --relay, --json",
    codeRef: "src/cli.ts:1832-1863",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Moderated general chat listing is asserted directly in live-commands."
  },
  {
    id: "FOR-016",
    area: "forum",
    feature: "Announce a private room",
    commands: "forum room announce",
    story: "As a forum participant, I want to announce a private room and its access code to other participants.",
    expectedBehavior: "The command resolves the forum, reads room announcement JSON, supports secret or signer auth, and publishes the announcement through the selected relays.",
    keyFlags: "--input, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1865-1899",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-017",
    area: "forum",
    feature: "List room announcements",
    commands: "forum room announcements",
    story: "As a forum participant, I want to list room announcements visible to the forum key.",
    expectedBehavior: "The command resolves the forum and returns room announcements for the selected salted or unsalted namespace.",
    keyFlags: "--password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1901-1921",
    tests: "tests/e2e/forum-live.test.ts:publishes room announcements and decrypts room chat with the shared access code",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct CLI coverage asserts decrypted room announcement fields including accessCode."
  },
  {
    id: "FOR-018",
    area: "forum",
    feature: "Send a room message",
    commands: "forum room send",
    story: "As a room participant, I want to send an encrypted chat message inside a private room using its access code.",
    expectedBehavior: "The command resolves the forum, reads room chat JSON, supports secret or signer auth, and publishes the encrypted room message for the named room.",
    keyFlags: "--input, --secret, --use-signer, --password, --salt, --relay, --json",
    codeRef: "src/cli.ts:1923-1955",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "FOR-019",
    area: "forum",
    feature: "List room messages",
    commands: "forum room list",
    story: "As a room participant, I want to decrypt and list private room messages and optionally apply moderation filtering.",
    expectedBehavior: "The command requires room name and access code, resolves the forum, lists room messages, and when --moderated is set filters them through WoT and banned-word rules.",
    keyFlags: "--room-name, --access-code, --moderated, --password, --profile-relay, --salt, --relay, --json",
    codeRef: "src/cli.ts:1957-1992",
    tests: "tests/e2e/live-commands.test.ts:forum commands publish posts replies torrents room flows and chat",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Moderated room message listing is asserted directly in live-commands."
  },
  {
    id: "XFN-001",
    area: "cross-cutting",
    feature: "Use passwords across runtime commands",
    commands: "inspect, verify, store *, petition *, fundraiser *, message *, forum *",
    story: "As a CLI user, I want encrypted Nowhere links to behave like the website by decrypting first and then running the downstream workflow.",
    expectedBehavior: "Runtime commands that accept site inputs should decrypt the site first when --password is passed and continue against the decrypted site.",
    keyFlags: "--password",
    codeRef: "src/cli.ts:370-392, 661-788, 930-1992",
    tests: "tests/e2e/live-commands.test.ts:encrypted runtime commands accept passwords across store petition fundraiser message and forum",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  },
  {
    id: "XFN-002",
    area: "cross-cutting",
    feature: "Accept encrypted fragments that start with a dash",
    commands: "all single-input fragment commands",
    story: "As a CLI user, I want encrypted fragments that begin with '-' to be treated as positional arguments without needing to insert '--' manually.",
    expectedBehavior: "Argument normalization should move a leading-dash positional input behind '--' when the current command expects a single positional argument and the token is not a known option.",
    keyFlags: "implicit argv normalization",
    codeRef: "src/cli.ts:308-344, 1994",
    tests: "README relay command guidance only",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: "Direct coverage now exercises decrypt, inspect, and verify with dash-prefixed encrypted fragments."
  },
  {
    id: "XFN-003",
    area: "cross-cutting",
    feature: "Persist forum anonymous session identity",
    commands: "forum post, forum chat send, forum private list",
    story: "As an anonymous forum participant, I want the CLI to reuse a stable session identity across posts, chat routing, and private inbox decryption.",
    expectedBehavior: "The CLI persists a generated forum session secret under XDG_CONFIG_HOME unless NOWHERE_FORUM_SESSION_SECRET or --session-secret overrides it for the relevant command.",
    keyFlags: "--session-secret, NOWHERE_FORUM_SESSION_SECRET",
    codeRef: "src/lib/forum-session.ts; src/cli.ts:1736-1814",
    tests: "tests/e2e/live-commands.test.ts:forum CLI reuses a persisted anonymous session for posts chat routing and private inbox decryption",
    coverageStatus: "Covered",
    storyStatus: "Cataloged",
    testStatus: "Passed",
    defectStatus: "None logged",
    fixCommit: "",
    retestStatus: "Passed",
    notes: ""
  }
];

export const errorLogColumns = [
  "Error ID",
  "Feature ID",
  "Area",
  "Command",
  "Observed Behavior",
  "Expected Behavior",
  "Repro Steps",
  "Severity",
  "Status",
  "Fix Commit",
  "Retest Result",
  "Notes"
];

export const errorLogEntries = [
  {
    "Error ID": "ERR-001",
    "Feature ID": "TEST-INFRA",
    "Area": "test harness",
    "Command": "e2e cwd resolution",
    "Observed Behavior": "Several e2e helpers executed the CLI in the sibling main checkout instead of the active feat/feature-audit worktree.",
    "Expected Behavior": "Branch-local test runs should execute src/cli.ts from the current checkout under test.",
    "Repro Steps": "Run pnpm test from the feature worktree and inspect the hard-coded cwd values in the e2e helpers.",
    "Severity": "P1",
    "Status": "Fixed",
    "Fix Commit": "",
    "Retest Result": "Passed",
    "Notes": "Fixed by resolving cwd from import.meta.url in create-long-form, generic, builders, and live-commands tests."
  },
  {
    "Error ID": "ERR-002",
    "Feature ID": "TEST-INFRA",
    "Area": "test harness",
    "Command": "petition-live timeout budget",
    "Observed Behavior": "The PoW-heavy petition runtime tests exceeded the original 30s inline timeout during branch-local runs.",
    "Expected Behavior": "PoW-heavy petition tests should have enough timeout headroom to pass when behavior is correct.",
    "Repro Steps": "Run pnpm test in the feature worktree and observe petition-live durations above 30s under full-suite conditions.",
    "Severity": "P2",
    "Status": "Fixed",
    "Fix Commit": "",
    "Retest Result": "Passed",
    "Notes": "Raised petition-live inline timeouts to 90s after confirming the logic passed."
  },
  {
    "Error ID": "ERR-003",
    "Feature ID": "TEST-INFRA",
    "Area": "test harness",
    "Command": "live-commands timeout budget",
    "Observed Behavior": "Expanded relay-backed integration coverage in live-commands exceeded the original 30s and 60s test budgets.",
    "Expected Behavior": "High-cost relay integration tests should have explicit timeout budgets that match observed branch-local runtime.",
    "Repro Steps": "Run pnpm test after the new live command coverage and observe timeouts in store and forum moderation integration tests even though targeted reruns pass.",
    "Severity": "P2",
    "Status": "Fixed",
    "Fix Commit": "",
    "Retest Result": "Passed",
    "Notes": "Raised slow live-commands timeouts to 60s and the expanded moderation integration test to 120s."
  }
];
